[build]
  publish = "public"
  functions = "src/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sailhouse/client"]

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
